on:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration-test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.17, 1.18]
        protocol: ['json', 'msgpack']

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download Packages
        run: go get -t -v ./ably/...

      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report@latest

      - name: Set env var for ablytest
        run: echo "ABLY_PROTOCOL=${{ matrix.protocol == 'json' && 'application/json' || 'application/x-msgpack' }}" >> $GITHUB_ENV
      
      - name: Integration Tests with ${{ matrix.protocol }} Protocol
        run: |
          set -o pipefail
          go test -tags=integration -p 1 -race -v -timeout 120m ./... |& tee >(~/go/bin/go-junit-report > ${{ matrix.protocol }}-integration.junit)

      - name: Upload test results
        if: always()
        uses: ably-labs/test-observability-action@main
        with:
          server-url: 'https://test-observability.herokuapp.com'
          server-auth: ${{ secrets.TEST_OBSERVABILITY_SERVER_AUTH_KEY }}
          path: '.'
